import {DefaultTheme} from '@react-navigation/native';
import {StyleSheet, Dimensions} from 'react-native';
const deviceWidth = Dimensions.get('screen').width;
const deviceHeight = Dimensions.get('screen').height;
const {width, height} = Dimensions.get('window');

export const theme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#600EE6',
    secondary: '#414757',
    error: '#f13a59',
  },
};

export const styles = StyleSheet.create({
  forgotPassword: {
    width: '100%',
    alignItems: 'flex-end',
    marginBottom: 24,
  },
  row: {
    flexDirection: 'row',
    marginTop: 4,
  },
  textinput: {
    color: '#191919',
    zIndex: -1,
    borderRadius: 5,
    paddingVertical:10,
    fontSize:14
  },
  label: {
    color: '#191919',
    fontWeight: '500',
    fontSize: 14,
    letterSpacing: 0.5
  },
  link: {
    fontWeight: 'bold',
    color: theme.colors.primary,
  },
  container: {
    width: '100%',
    marginVertical: 12,
  },
  input: {
    backgroundColor: theme.colors.surface,
    zIndex: -1,
  },
  error: {
    fontSize: 14,
    color: theme.colors.error,
    paddingHorizontal: 4,
    paddingTop: 4,
  },

  scrollViewStyle: {
    flex: 1,
    justifyContent: 'flex-start',
    backgroundColor: '#2196f3',
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: '10%',
    paddingLeft: 15,
    paddingTop: 10,
    width: deviceWidth,
  },
  hederTitle: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
    maxWidth: width * 0.75,
    marginVertical: 2,
    marginHorizontal: 25,
    letterSpacing: 0.75,
  },
  textTitle: {
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    padding: 16,
    color: 'white',
  },
  textTitle1: {
    fontWeight: 'bold',
    fontSize: 18,
    textAlign: 'center',
    padding: 16,
    color: 'white',
  },
  cardView: {
    width: deviceWidth - 32,
    height: deviceHeight - 350,
    alignSelf: 'center',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderRadius: 10,
    padding: 25,
    marginLeft: 5,
    marginRight: 5,
    marginTop: '10%',
    backgroundColor: 'white',
  },
  scanCardView: {
    width: deviceWidth - 32,
    height: deviceHeight / 2,
    alignSelf: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    padding: 25,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 10,
    backgroundColor: 'white',
  },
  buttonWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  buttonScan: {
    borderWidth: 2,
    borderRadius: 10,
    borderColor: '#258ce3',
    paddingTop: 5,
    paddingRight: 25,
    paddingBottom: 5,
    paddingLeft: 25,
    marginTop: 20,
  },
  buttonScan2: {
    marginLeft: deviceWidth / 2 - 50,
    width: 100,
    height: 100,
  },
  descText: {
    padding: 16,
    textAlign: 'center',
    fontSize: 16,
  },
  highlight: {
    fontWeight: '700',
  },
  centerText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    padding: 32,
    color: 'white',
  },
  textBold: {
    fontWeight: '500',
    color: '#000',
  },
  bottomContent: {
    width: deviceWidth,
    height: 120,
  },
  buttonTouchable: {
    fontSize: 21,
    backgroundColor: 'white',
    marginTop: 32,
    width: deviceWidth - 62,
    justifyContent: 'center',
    alignItems: 'center',
    height: 44,
  },
  buttonTextStyle: {
    color: 'black',
    fontWeight: 'bold',
  },
  loaderOuterWrapper: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    top: 0,
    left: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.81)',
  },

  loaderInnerWrapper: {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  //scanner styles
  screen: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  saveArea: {
    backgroundColor: '#62d1bc',
  },
  topBar: {
    height: 50,
    backgroundColor: '#002B5B',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topBarTitleText: {
    color: '#ffffff',
    fontSize: 20,
  },
  caption: {
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
  },
  captionTitleText: {
    color: '#121B0D',
    fontSize: 16,
    fontWeight: '600',
  },
  homeBtnContainer: {
    borderRadius: 25,
    backgroundColor: '#8E05C2',
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginVertical: 20,
    marginHorizontal: 20,
    width: 200,
  },
  homeBtnText: {
    fontSize: 18,
    color: '#ffffff',
    textAlign: 'center',
    fontWeight: '700',
  },
  logotext: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#8E05C2',
    marginBottom: 20,
    letterSpacing: 1,
  },
  btn: {
    borderRadius: 4,
    backgroundColor: '#3D56B2',
    paddingHorizontal: 20,
    paddingVertical: 12,
    marginVertical: 20,
    marginHorizontal: 20,
  },
  cancelBtn: {
    borderRadius: 4,
    backgroundColor: '#FF0000',
    paddingHorizontal: 24,
    paddingVertical: 12,
    bottom: 0,
  },
  btnText: {
    fontSize: 18,
    color: '#ffffff',
    textAlign: 'center',
  },
  rnCamera: {
    width: 275,
    height: 275,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    overflow: 'hidden',
  },
  rmCameraResult: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#eeeeee',
  },
  rmCameraResultText: {
    fontSize: 20,
    color: '#62d1bc',
  },
  cameraControl: {
    height: 120,
    justifyContent: 'space-around',
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
  },
  formContainer: {
    flex: 1,
    marginHorizontal: 10,
    marginVertical: 20,
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: 'white',
  },
  submitBtn: {
    borderRadius: 5,
    backgroundColor: '#3D56B2',
    paddingVertical: 7.5,
    marginVertical: 20,
    width: 120,
  },
  headerContainer: {
    backgroundColor: '#002B5B',
    paddingHorizontal: 5,
    paddingVertical: 15,
    display: 'flex',
    flexDirection: 'row',
  },
  rnholeView: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  //dropdownstyles
  filterModelContentStyle: {
    width,
    height: height * 0.75,
    backgroundColor: 'white',
    overflow: 'hidden',
    paddingHorizontal: 15,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 12,
    },
    shadowOpacity: 0.58,
    shadowRadius: 16.0,
  },
  inputContainerWrapper: {
    marginBottom: 20,
  },
  inputLabel: {
    color: '#707184',
    fontWeight: '700',
    fontSize: 16,
  },
  flatListContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  inputContainer: {
    backgroundColor: '#FFF',
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 5,
    paddingHorizontal: 20,
    paddingVertical: 15,
    color: 'black',
    textAlignVertical: 'top',
  },
  errorText: {
    fontSize: 10,
    textAlign: 'left',
    color: 'red',
  },
  broadcastModalContainer: {
    backgroundColor: 'rgba(0,0,0,0.2)',
    flex: 1,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textShadow: {
    fontSize: 16,
    fontWeight: '400',
    color: '#707184',
  },
  dropdownItem: {
    paddingVertical: 10,
    paddingLeft: 10,
  },
  selectedDropdownText: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  pillsButtonContainer: {
    alignSelf: 'center',
    borderRadius: 15,
    marginHorizontal: 2,
  },
  pillsContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  pillsButtonText: {
    color: 'white',
    fontWeight: '700',
    fontSize: 8,
    marginLeft: 2,
  },
  statusButtonContainer: {
    alignSelf: 'center',
    borderRadius: 15,
  },
  statusContainer: {
    alignItems: 'center',
    flexDirection: 'row',
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  statusButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 10,
    marginLeft: 2,
  },
  modalContainer: {
    width,
    height,
    backgroundColor: '#00000099',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  modalStyles: {
    margin: 15,
  },
  documentUpload: {
    fontSize: 12 * 1,
    fontWeight: 'bold',
    fontFamily: 'rubik',
    padding: 10,
    borderRadius: 5,
  },
  loginContainer: {
    backgroundColor: '#FFF',
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    flexDirection: 'column',
  },
  loadingContainer: {
    flex: 1,
    flexGrow: 1,
    justifyContent: 'center',
  },
  forgotTextStyle: {
    color: '#3b8ba5',
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'right',
    letterSpacing: 0.5
  },
  headerText: {
    color: '#191919',
    fontSize: 35,
    fontWeight: '700',
    textAlign: 'center',
    letterSpacing: 2,
  },
});
