import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

export const genericStyles = StyleSheet.create({
  tableContainer: {
    flexDirection: 'row',
    display: 'flex',
    alignSelf: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 5,
  },
  tableHeaderText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#475569',
  },
  tableText: {
    fontSize: 14,
    color: '#000000',
  },
  container: {
    flex: 1,
    backgroundColor: '#E8E4F0',
    zIndex: 0,
  },
  dateContainer: {
    backgroundColor: 'white',
    paddingVertical: 16,
  },
  label: {
    position: 'absolute',
    backgroundColor: 'white',
    left: 7,
    top: 8,
    zIndex: 999,
    paddingHorizontal: 5,
    fontSize: 14,
  },
  pageheaderText: {
    color: '#A0A0A0',
    fontWeight: 'bold',
    letterSpacing: 0.5,
    fontSize: 30,
  },
  btnContainer: {
    borderRadius: 20,
    backgroundColor: '#A855F7',
    borderColor: '#FFFFFF',
    elevation: 4,
    marginVertical: 10,
    width: width * 0.3,
  },
  businessBtnContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderColor: '#FFFFFF',
    alignItems: 'center',
    marginVertical: 10,
  },
  customerCardContainer: {
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  orderTextContainer: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'space-between',
    rowGap: 10,
  },
  homeSectionText: {
    color: '#334155',
    fontSize: 18,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  homeSectiondesc: {
    color: '#475569',
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0.5,
    marginBottom: 20,
  },
  divider: {
    color: '#5C5D72',
    fontWeight: 'bold',
  },
  selectedImageContainer: {
    alignSelf: 'center',
    borderRadius: 20,
    elevation: 4,
    position: 'relative',
  },
  selectedImagestyle: {
    height: 150,
    width: 150,
    resizeMode: 'contain',
    borderRadius: 20,
  },
  docIconStyle: {
    borderRadius: 5,
    borderColor: '#ff5722',
    position: 'absolute',
    top: 5,
    right: 5,
  },
  docTextStyles: {
    color: '#475569',
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.5,
    marginHorizontal: 20,
    width: 150,
  },
  docButtonStyle: {
    borderRadius: 5,
    borderColor: '#A855F7',
    elevation: 4,
    marginVertical: 10,
    width: '50%',
    borderWidth: 1,
  },
  docBtnContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  deleteBtnContainer: {
    borderRadius: 10,
    backgroundColor: '#ff5722',
    elevation: 4,
    // marginVertical: 10,
    width: width * 0.3,
  },

  //modal styles
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.75)',
  },
  modalView: {
    marginHorizontal: 10,
    backgroundColor: 'white',
    borderRadius: 15,
    padding: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '85%',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalButtonsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  deleteBtnStyles: {
    borderRadius: 10,
    backgroundColor: '#ff5722',
    elevation: 4,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontWeight: '500',
    fontSize: 15,
    color: '#191919',
  },
  modalImageStyle: {
    borderRadius: 5,
    width: width * 0.22,
    height: height * 0.09,
    marginVertical: 10,
  },
  errorText: {
    fontSize: 12,
    fontWeight: '400',
    color: '#f13a59',
    marginVertical: 5,
  },

  tableHeaderContainer: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  multiDeleteBtnContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: width * 0.45,
    height: height * 0.06,
    alignItems: 'center',
    // columnGap: 3,
  },
  multiDeleteText: {
    color: '#A0A0A0',
    fontWeight: '400',
    letterSpacing: 0.3,
    fontSize: 15,
  },
  searchBarStyles: {
    backgroundColor: '#FFFFFFF',
    borderWidth: 1,
    borderColor: '#CCCCCC',
    height: height * 0.05,
    textAlign: 'auto',
  },

  noDataFoundImage: {
    borderRadius: 5,
    width: '80%',
    height: '80%',
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  loaderContainer: {
    backgroundColor: 'white',
    borderRadius: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '45%',
    height: '20%',
    display: 'flex',
    justifyContent: 'center',
  },
  loaderImage: {
    width: '50%',
    height: '50%',
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  cancelBtnContainer: {
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#f13a59',
    marginVertical: 10,
    borderRadius: 20,
  },
  searchBarContainer: {
    display: 'flex',
    flexDirection: 'row',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#CCCCCC',
    width: width * 0.4,
    height: height * 0.06,
    overflow: 'scroll',
  },
  filterContainer: {
    backgroundColor: '#FFFFFF',
    height: '70%',
    width: '96%',
    bottom: 0,
    position: 'absolute',
    borderTopRightRadius: 15,
    borderTopLeftRadius: 15,
    shadowColor: '#FFFFFF',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    alignSelf: 'center',
    marginHorizontal: 10,
  },
  filterHeaderContainer: {
    padding: 5,
    marginBottom: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  filterHeadertext: {
    fontSize: 20,
    fontWeight: '600',
    color: '#191919',
    letterSpacing: 1,
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    columnGap: 20,
    padding: 10,
  },
  filterButtonsStyles: {
    borderRadius: 20,
    backgroundColor: '#A855F7',
    borderColor: '#FFFFFF',
    elevation: 4,
    marginVertical: 10,
  },
  richtextLabel: {
    color: '#62538C',
    margin: 5,
    fontSize: 14,
    fontWeight: '400',
  },
  documentLabel: {
    color: '#62538C',
    fontSize: 16,
    fontWeight: '400',
  },
});
